### ISSUE TITLE
patches-vector-0.1.0.0 test suite failure

### ISSUE THREAD

**Issue by peti** [liamoc/patches-vector#1]
Citing from http://hydra.cryp.to/build/1318177/log/raw:

```
running tests
Running 1 test suites...
Test suite test-patches-vector: RUNNING...
### Failure in Data/Patch/Internal.hs:65: expression `apply (fromList [Insert 0 'a', Insert 1 'b']) (Vector.fromList "123")'
expected: "a1b23"
 but got: fromList "a1b23"
Examples: 23  Tried: 22  Errors: 0  Failures: 1
Test suite test-patches-vector: FAIL
```

**Comment by liamoc** [comment]
Any reason why you're using vector 0.10? It's just a difference in the `Show` instance for vector-0.10 vs vector 0.11

**Comment by liamoc** [comment]
My cabal file excludes vector-0.10

**Comment by peti** [comment]
I use it because `vector-0.10` is mandated by http://www.stackage.org/.

**Comment by peti** [comment]
Anyway, I suppose the bug report is invalid since your Cabal file excludes 0.10. Thank you for the quick response.

**Comment by liamoc** [comment]
Even so, you can probably still use the library with vector-0.10. That test failure is harmless.

**Comment by liamoc** [comment]
Note, version 0.1.0.1 should fix this problem as it's been fixed to work with LTS haskell.
