### ISSUE TITLE
patch normalization seems wrong or unintuitive

### ISSUE THREAD

**Issue by stepcut** [liamoc/patches-vector#6]
I can't tell if patch normalization is broken, or I just do not understand how it should work. If I create the following patch:

```
> apply (Data.Patch.fromList [ Insert 0 'a', Insert 0 'b', Delete 0 'b', Insert 0 'c', Delete 0 'c' ]) mempty
"c"
```

I would expect `"a"` not `"c"`. My assumption is that edits are applied left to right. So I would expect that the `"a"` would remain and the `Insert/Delete` for `"b"` and `"c"` would cancel themselves out.

Is this a bug in my understanding or in the code?

**Comment by stepcut** [comment]
This version of normalise is more what I would expect:

```
-- | Eliminate conflicting edits
--
-- NOTE: the function assumes that all the indices are the same -- see 'fromList'
normalise2 :: [Edit a] -> [Edit a]
normalise2 [] = []
normalise2 es = go es []
  where
    go (x@(Insert _ new):xs) acc =
      case acc of
        -- delete followed by insert is a replace
        (a@(Delete i old):as) -> go xs (Replace i old new:acc)
        _ -> go xs (x:acc)
    go (x@(Delete {}):xs) acc =
      case acc of
        -- insert followed by delete is a noop
        (a@(Insert {}):as) -> go xs as
        _ -> go xs (x:acc)
    go (x:xs) acc = go xs (x:acc)
    go [] acc = reverse acc
```

I don't make any claims the implementation is efficient. I basically just use a list as a stack and push edits on to the stack. However, before doing so, I check the head of the stack and see if the new edit and the head of the stack combine in some way. An `Insert` followed by a `Delete` is a noop, so I just pop the element off the stack. A `Delete` followed by an `Insert` is a `Replace` -- so I pop the head element and push a `Replace`.

**Comment by liamoc** [comment]
> I would expect "a" not "c". My assumption is that edits are applied left to right. So I would expect that the "a" would remain and the Insert/Delete for "b" and "c" would cancel themselves out.
> 
> Is this a bug in my understanding or in the code?

In you understanding. All the indices in the patch are relative to the original, unedited document. So it's impossible for a Delete to undo an Insert in the same patch.

**Comment by stepcut** [comment]
I guess I would suggest that the current API is very fragile?

Is the `Patch` I manually created simply invalid?

I don't really understand how the 'relative to the unedited original' thing works. Let's say my original document is empty. And I want to insert as "abc" into an empty document. So relative to the original document wouldn't that mean, a=0, b=1,c=2?

```
Prelude Data.Patch> apply (Data.Patch.fromList [Insert 0 'a', Insert 1 'b', Insert 2 'c']) (Data.Vector.fromList "")
"aSegmentation fault: 11
```

That actually crashes GHCi.

Instead I have to write:

```
Prelude Data.Patch> apply (Data.Patch.fromList [Insert 0 'a', Insert 0 'b', Insert 0 'c']) (Data.Vector.fromList "")
"abc"
```

But, it is also not clear why that should produce "abc" instead of "cba". If each character was being inserted at position 0 I would expect:

```
a
ba
cba
```

I've also noticed that it is very easy to cause memory errors using hand constructed patches. In addition to the above example, there is also this:

```
Prelude Data.Patch> apply (Data.Patch.fromList [Delete 0 'g']) (Data.Vector.fromList "")
""
Prelude Data.Patch> Bus error: 10
```

In my particular use case I am trying to build the patch on the fly as the user types.

**Comment by liamoc** [comment]
>  And I want to insert as "abc" into an empty document. So relative to the original document wouldn't that mean, a=0, b=1,c=2?

No, because 1 and 2 are invalid indices in an empty document. You'd want the index to be 0 in all three edits. 

> produce "abc" instead of "cba"

The order of simultaneous inserts is resolved as the order in which they appear in the patch. So long as patches are always processed left-to-right, this works.

The idea is that patch intersection shouldn't require adjusting indices of any edit. This is incredibly useful for transform.

> In my particular use case I am trying to build the patch on the fly as the user types.

In that case, I would suggest composing the patches together, rather than keeping it as a list of edits. That will probably do what you want.

```
 P.fromList [Insert 0 'a'] <> P.fromList [Insert 1 'b'] <> P.fromList [Insert 2 'c'] == P.fromList [Insert 0 'a', Insert 0 'b', Insert 0 'c']
```

Lastly, this example should obviously fail

> apply (Data.Patch.fromList [Delete 0 'g']) (Data.Vector.fromList "")

Because that patch is not a valid patch for that document. If you want to guard against these errors, use the `applicable` and `composable` utility functions.

**Comment by liamoc** [comment]
Patch resolution happens in zero time. Each edit in a particular patch is independent of any other edit. There is no telescopic dependency. E.g a patch `P.fromList [a,b,c]`, if I remove the edit `a`, the edits `b` and `c` will work correctly unchanged, because they don't depend on `a`. 

What you seem to want is a telescopic dependency, where each edit depends on all previous edits. To make that kind of list into a patch, use `mconcat . map (P.fromList . pure)` rather than `P.fromList`

**Comment by stepcut** [comment]
Thanks! I believe I understand now. Adding these bits to the haddock docs would be incredible valuable:

> Patch resolution happens in zero time. Each edit in a particular patch is independent of any other edit. There is no telescopic dependency. E.g a patch P.fromList [a,b,c], if I remove the edit a, the edits b and c will work correctly unchanged, because they don't depend on a.
> 
> The order of simultaneous inserts is resolved as the order in which they appear in the patch. So long as patches are always processed left-to-right, this works.
> 
> The idea is that patch intersection shouldn't require adjusting indices of any edit. This is incredibly useful for transform.

Also, explaining why that means the order of the `Insert` and `Delete` in these examples does not change the results:

```
Prelude Data.Patch> apply  (Data.Patch.fromList [Insert 0 'a', Insert 2 'b' ]) (Data.Vector.fromList "123")
"a12b3"
Prelude Data.Patch> apply  (Data.Patch.fromList [Insert 0 'a', Delete 0 '1', Insert 2 'b' ]) (Data.Vector.fromList "123")
"a2b3"
Prelude Data.Patch> apply  (Data.Patch.fromList [Delete 0 '1', Insert 0 'a', Insert 2 'b' ]) (Data.Vector.fromList "123")
"a2b3"
```

might be a helpful illustration.

It would also be nice if the haddock docs for `Edit` and/or `apply` noted that an invalid `Patch` can result in a serious runtime error.

I can attempt the updates myself and submit a pull request if you'd like.

**Comment by liamoc** [comment]
Alright, I'll have a go at updating the docs probably next week. If you want to take it on before then, I'll accept your patches.
